# Generated by Django 3.2.7 on 2022-03-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('stock', models.CharField(max_length=20)),
                ('open_p', models.FloatField()),
                ('high_p', models.FloatField()),
                ('low_p', models.FloatField()),
                ('close_p', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
