# Generated by Django 3.2.7 on 2022-04-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0005_articletest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articletest',
        ),
    ]
