# Generated by Django 3.2.7 on 2022-04-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0007_articletest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articletest',
        ),
    ]
